Changed doortext to middle of door
qbcore-framework/qb-doorlock pull request #138
Opened 2023-01-09 02:24 UTC by ChristianBDev

**Describe Pull request**
This changed on line 88 in the client/main.lua stating to change the text in the middle of the door instead of the corners of the door to make it unlikely to see.

**If your PR is to fix an issue mention that issue here:**
This was for BUG[#137] stating it was in corner of door and was in the red now in the green/middle of the door

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

2023-01-09 02:31 UTC, charj commented
Code makes sense. 
Haven't tested as of yet.
@KamuiKody volunteered to test :)

2023-01-09 03:18 UTC, KamuiKody approved these changes
Works Great Tested in my server! good fix

2023-01-11 10:28 UTC, Z3rio approved these changes

2023-01-18 04:56 UTC, KamuiKody approved these changes
Works fine for me

2023-01-25 15:33 UTC, zwkf approved these changes
LGTM

2023-01-27 12:34 UTC, zwkf approved these changes

2023-02-07 03:35 UTC, zwkf approved these changes

2023-02-10 00:06 UTC, zwkf requested changes
test

2023-02-10 00:06 UTC, zwkf approved these changes

2023-02-17 01:35 UTC, zwkf approved these changes
LGTM

2023-05-14 06:14 UTC, YG0007 requested changes
the if condition can be removed as the function is returning the same

2023-10-01 15:41 UTC, closed without merging